sudo: required

services:
- docker

script:
- make container

before_deploy:
- docker login -u $DOCKER_USER -p $DOCKER_PASS

deploy:
- provider: script
  script: make push
  on:
    tags: true

env:
  global:
  - secure: dKCXFAq6q/OiUVRuEOARXXAO5hFgFdQF6kGjPgWfVwvqbvmMjM4E5ffSWVbrimcjZBHFVBlTBKdPOgUmi7mk4IgdtU3GE2UW5lVhhQ1vOOhK+mgfkaKSsbNu/IGJzqZ7IMTaTW69Tu5JdHDh3JkOc3cA55u3cV8Jm8TPA4ROQ6cKsrXJr6eyQ0EmczG+xQ8R7FkqA8OAyxtq/t4idX9X/hoodrXaao5lbszKldIh/YgCHLbkffnCKFvJblyTEfpd7BiVzeY+9T8N5iio3hWFaKPxpBAezShnnFmE/w80cz5Y9BXAnqzrx4Ks2by2Oxt8BLEgZ3jYJlEw2odrR8jynubR96i8MPPGwXaKgwB34L+phi9X8iZViURqX9l5ad0qNdauF2flplZ3SjFrVROIMrTdHk4qseh67tE935MGEkWtozSeNk7hAWT8Gwe08VZ7EveroJIYgTPG+8vK9+dB9WSZGeg/rVZR0kL+GRJS5onO/RwT8mBHkvOH+SdTjMonyagTu/WNhhKFzug5CLtV4wQB0fB6oYOxR6DPg41qf2vbx3ynbchkE3xtHAUqUtnyZ0hJLACX7c0tX2wX0JVbLYfHz0yQx4Tx5P+UzZn1S7hiFVh7szt9HtG8Q8OyyFMBPiL9Kz+rEiQ8rkU/b1GK6K7unQihq1N8Z1juCfLbHTY=
  - secure: BlhpDHMcSUWk/QHYQH//L7S9EoOQoo+Of48RjKK/cxFFjyAIXq/Ubun6wIcv8CrWAm8K5aGL+Q3Oah0zqL3PnjCbCdIsQOSMPi9yiEQ9PBw8MwfSai9ILuWisuU5iiySpljNgnXgh8jvpPYW0VVAsVkMZbaD5hpwzNdMRFmH+1Ynbt/MKw5niTb6/1nUFtB6q5BuSjhNY8V1B4AWOjZtogH7LkX4d7G3rQG7PqV3n/uxdKunAJtO1oByoqz+STlKrVF588hZHSLKa8uENTERhz+tfRhi1cBdOU4e9SXFTZxYFAJ0yGSXnm/E1ZmkW1fD/MJCjBuVtdf/s4dZfM5ziuUHwU4em2VwwK7pfjVTQs/R7xLeRpNFdOTlqjqtBKHPzMmv940JCXpNHMpa2zf1N/1uzY+RWcEnHEDqBBfkGEecgEhNwWeopQbMuahYZhLyXx5E7k68RTED0pwPDRwgmTdVrxTp5h6AenE0zTo42ueMhp6vlX7PuPAKuJZquYW1EcriCoGhelOGU0ZBZP/kSGm91/ZlkrEfmvIzP3TSOti2SAAVQIefTvQhPR2rMJLD+CgyX2+iEQ9McdwApt1llC+r5netMu6PUCWiFrlJGE6TmsOi6v0rEk/QW0nXfqd/Hv/KorLphkk2QO8DL6B6P5Pb4bv3DtVI6aN9dPYJcv8=
  - secure: IVkeHAHKKJLkek2avQTPCOEzWsAgtGgszL7oCV69GrF43WzQxqHzmKQY8ZEMGaZYJ308fnqx+WnLeH++238JHFC443RsgZ2jfs05mvTHnMOyI18BfY7mL5rm9T8LTiy46T41XDq5LLlqjsP6t7xsG/JOudr7um3RX3ZN352j+TwBX5bqzjNisYnL9l5cdK+1C+ZZ/hMi83OthLfP19kGmxlfn6bSMBzaFBLjWp3WBIjrTFDPmz0U1wWCLc5ZxJU8Ub179h7xiBf/uvYdP8dXfkw6RQ9Lul8IMklbNRYtVCXIcRCClOX5dibQHC35HjnKvPwoxrXE8sK+MJu0diJtQOjQOTFmhKLYzV6kcvnlgcMG3v7pFi/FrQ9AXeyOV8Jk+s+wclOB7UzbuGuvl0zfae0bkB223VIug1Nzu73sznyqgzLF8O2p+qFS/99huM7flw42VqxI7oVdgRLrBPq5VpSAMCz44sDxmNJ0c+YDWuzSYvoSiDmF+WcMZYb72Q6x3EZy4ynKmWCYlaPdyxWyyVJPk85dJ3BONYRKQEkaH0AWwSSiNqxKk5DAQXHSJh2UgLR/Oi+u0i3/sM/V07kOYTgPhyl28kTUy4USCr1X2CQOaFuyM/WwxlkMkT46oTJC1ccipoOZsJX61fXCYM/7YXEmPJdiqtffJHWCIJA+fEk=
